# \file
# Makefile
#
# Copyright (c) 2006   Regents of the University of California
#

#include $(CAPATH_MK_DEFS)
include capath_qnx.mk

all:	$(OBJDIR)

$(OBJDIR): 
	mkdir -p $(OBJDIR)

clean:
	rm -rf $(OBJDIR)/*.a 
